### ISSUE TITLE
xbot posts all RITlug meetings into #ritlug on each website PR

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/ritlug.github.io#158]
## Issue
![xbot_ritlug_site](https://user-images.githubusercontent.com/22552344/44619107-595dc380-a84f-11e8-92ea-0c74207f04ba.png)

## Additional Details
On each PR xbot decides to post all meetings one after another. One potential reasoning for this is when post IDs change, xbot thinks these are all new announcements.

**Comment by ct-martin** [comment]
According to @thenaterhood, xbot uses the UUID field of RSS feeds to identify posts. In the last couple PRs we have turned on "pretty links" (no `.html` in the file path) and HTTPS in the Jekyll config's base url (which it uses to generate absolute paths). Since the site uses the absolute path of the post for its UUID (fairly common practice), this has caused the UUID to change, which makes xbot think that there are new posts. It seems that IFTTT is smart enough to catch this, so our mailing list has not been spammed. I am closing this issue since this shouldn't happen again, but another issue should be opened if it does.

Additionally, Flory doesn't manage the website code so you shouldn't assign technical issues to him :P
