### ISSUE TITLE
Populate ICAL Feed

### ISSUE THREAD

**Issue by jrtechs** [RITlug/ritlug.github.io#176]
We would like to populate the ICAL feed with events for this semester and link it on our website.

**Comment by ct-martin** [comment]
Also calendar page w/ event list

**Comment by jrtechs** [comment]
@ct-martin What needs to be done to add an event to the ICAL feed?

**Comment by ct-martin** [comment]
@jrtechs this issue is on me, but the metadata of `date-start`, `date-end`, etc. from a number of places will automatically add themselves to the feed. I think I'm going to split this issue into two PRs given how it's working out so far in displaying a large amount of info, one to add the events, and another to display them somewhere on the site.

**Comment by ct-martin** [comment]
@jrtechs more info:

example: https://github.com/RITlug/ritlug.github.io/blob/master/meetings-meetups/_posts/2018-10-27-project-collab.md
code: https://github.com/RITlug/ritlug.github.io/blob/master/feeds/calendar.ics
