### ISSUE TITLE
Add link to Discord

### ISSUE THREAD

**Issue by zethra** [RITlug/ritlug.github.io#300]
We should add a link to the Discord since that's our primary mode of communication now.

**Comment by zethra** [comment]
Me may also want to remove the slack link since almost no one uses it.

**Comment by jrtechs** [comment]
I agree. We were hesitant about posting the join link at first due to spam. But, it has been public in the ritlug announcements for some time and we haven't gotten any spam yet. However, I think there might still be room for concern with spam as discussed in discord forums in the past. 

https://www.reddit.com/r/discordapp/comments/94q293/regarding_recent_bot_activity/

I think we should be mostly good. However, I think it would be a good idea to set up a server staging area where members have to react to a message to receive permissions to view other channels and send messages. Reacting to the message will give them the status of the member, and we can potentially use this to assign roles.

**Comment by MoralCode** [comment]
That can be done pretty easily with carlbot. I have a similar setup on another server.

I think discords new built in automod should also help curb spam

**Comment by zethra** [comment]
When I was e-board we didn't want to use carlbot because it isn't FOSS.

**Comment by ryan77627** [comment]
Discord link is on the website, closing this issue
